### ISSUE TITLE
Wheels for python 3.7

### ISSUE THREAD

**Issue by skoudoro** [KitwareMedical/VTKPythonPackage#28]
Hi VTKPython team, 

Thanks for this work! 

Is it possible to add python3.7 wheel on Pypi and Conda-Forge.  Python37 is the last release and any new installation generate this error:

```
Collecting vtk>=8.1.0 (from fury)
  Could not find a version that satisfies the requirement vtk>=8.1.0 (from fury) (from versions: )
No matching distribution found for vtk>=8.1.0 (from fury)
```

This is on a Mac with OS 10.14 and Python 3.7

Thank you

**Comment by thewtex** [comment]
Hi @skoudoro ,

We will need the next release of VTK (should be coming soon), which adds support for 3.7.

CC: @prabhuramachandran @jcfr @dgobbi @demarle

**Comment by jcfr** [comment]
Thanks to @prabhuramachandran , wheels for vtk 8.1.2 are available.

**Comment by skoudoro** [comment]
Awesome! Thank you @prabhuramachandran and all the team!
